### ISSUE TITLE
CI Runner update

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/puppet-gitlab#120]
Currently the method of checking `config.toml` for runner exists or not needs to be fixed.
While this works for the existence of a runner it doesn't allow for any changes to the runner itself.
The addition of options, tags, image, etc won't generate updated `config.toml`

It appears somehow the runner hash needs to be compared to current found hash in the `config.toml` to determine if the runner has updated or not.

To reproduce:

```yaml
gitlab_ci_runners:
  ruby2.1:
    docker-image: "ruby:2.1"
gitlab_ci_runners_defaults:
  url: "https://gitlab.host/ci"
  registration-token: "XXXX"
  executor: "docker"
  docker-image: "ubuntu:trusty"
```

to 
```yaml
gitlab_ci_runners:
  ruby2.1:
    docker-image: "ruby:2.FOO"
    tag-list:
      - "ruby2.1"
gitlab_ci_runners_defaults:
  url: "https://gitlab.host/ci"
  registration-token: "XXXX"
  executor: "docker"
  docker-image: "ubuntu:trusty"
```

Will not update the config.toml to the following:

```yaml
concurrent = 4
check_interval = 0

[[runners]]
  name = "ruby2.1"
  url = "https://gitlab.host/ci"
  token = "XXXX"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ruby:2.FOO"
    privileged = false
    disable_cache = false
  [runners.cache]
```

Also the tag update for the runner isn't something that gets written to `config.toml` but updated in gitlab so that needs to be checked as well.

Only solution so far would be to empty `config.toml` and delete the runners in Gitlab UI... then run puppet and it will recreate the runners with current configuration and proper tags.
