### ISSUE TITLE
Omniauth configuration misformated with extra quotes

### ISSUE THREAD

**Issue by InfernoZeus** [voxpupuli/puppet-gitlab#140]
I'm trying to configure this module with Omniauth settings for Github. I've added this to my Hiera yaml:
```
gitlab::gitlab_rails:
  omniauth_enabled: true
  omniauth_allow_single_sign_on: true
  block_auto_created_users: true
  omniauth_providers:
    - name: github
      app_id: xxx
      app_secret: xxx
      url: https://github.com
      args: "{ 'scope' => 'user:email' }"
```
The resulting gitlab.rb however is misformated:
```
gitlab_rails['omniauth_providers'] = '[
    {
        'name' => 'github',
        'app_id' => 'xxx',
        'app_secret' => 'xxx',
        'url' => 'https://github.com',
        'args' => { 'scope' => 'user:email' }
    }
]'
```
Notice the extra quotes around the list. How can I avoid these being injected?
