### ISSUE TITLE
rack_attack whitelist

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/puppet-gitlab#143]
I've run into issue where my puppetmaster using code-manager is polling a lot of repositories and branches for deployment. Therefore it keeps getting caught and blocked periodically.
I'm looking for how to implement the rack_attack whitelist.

I've tried using the following in gitlab.rb:

```ruby
gitlab_rails['rack_attack_git_basic_auth'] = {"bantime"=>"3600", "enabled"=>true, "findtime"=>"60", "ip_whitelist"=>["127.0.0.1"], "maxretry"=>"10"}
```
by using the following in hiera:

```yaml
gitlab::gitlab_rails:
  rack_attack_git_basic_auth:
    enabled: true
    ip_whitelist:
      - '127.0.0.1'
    maxretry: '10'
    findtime: '60'
    bantime: '3600'
```

but it seemed to make things worse and developers trying to push code were now getting blocked.
Any ideas?
