### ISSUE TITLE
Boolean flags to gitlab-runner cannot be passed

### ISSUE THREAD

**Issue by jessereynolds** [voxpupuli/puppet-gitlab#260]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: any
- Module version: 2.1.0

## How to reproduce (e.g Puppet code you use)

Hiera data for a node:

```yaml
gitlab_ci_runners:
  docker_puppet:
    url: 'https://gitlab.example/'
    registration-token: xxxxxxxx
    executor: docker
    docker-image: ruby:2.5
    tag-list: "puppet"
    run-untagged: true
```

## What are you seeing

The `--run-untagged` option is passed to `gitlab-runner register` with a value of `true`

## What behaviour did you expect instead

The `--run-untagged` option should be passed without a value as it does not take one.

## Suggestion

Perhaps a set of boolean flags could be passed in a specifically named key in the config hash such as `boolean_flags`
