### ISSUE TITLE
Multiple environment variables cannot be passed to gitlab-runner

### ISSUE THREAD

**Issue by jessereynolds** [voxpupuli/puppet-gitlab#261]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: any
- Module version: 2.1.0

## Problem

There is no nice way to specify a runner config hash that results in multiple `--env FOO=BAR` options passed to the `gitlab-runner register ... ` command. This is because each parameter is represented as a hash key and you can not have duplicate keys in a hash. The below hiera yaml shows a very hacky workaround to achieve this, but this is horrible. 

Hiera data for a node:

```yaml
gitlab_ci_runners:
  docker_puppet:
    url: 'https://gitlab.example/'
    registration-token: xxxxxxxx
    executor: docker
    docker-image: ruby:2.5
    env: "HTTP_PROXY=%{proxy} --env HTTPS_PROXY=%{proxy} --env NO_PROXY=gitlab.example"
```

## Suggestion

Perhaps a key `unstructured_parameters` containing an array could be handled, eg:

```yaml
gitlab_ci_runners:
  docker_puppet:
    url: 'https://gitlab.example/'
    registration-token: xxxxxxxx
    executor: docker
    docker-image: ruby:2.5
    unstructured_parameters: 
    - env HTTP_PROXY=%{proxy}
    - env HTTPS_PROXY=%{proxy}
    - env NO_PROXY=gitlab.example
```

Or a special hash for environment variables: 

```yaml
gitlab_ci_runners:
  docker_puppet:
    url: 'https://gitlab.example/'
    registration-token: xxxxxxxx
    executor: docker
    docker-image: ruby:2.5
    environment_variables: 
      HTTP_PROXY: %{proxy}
      HTTPS_PROXY: %{proxy}
      NO_PROXY: gitlab.example
```
