### ISSUE TITLE
Hiera not parsing gitlab.rb and ::gitlab_rails:

### ISSUE THREAD

**Issue by hktyper** [voxpupuli/puppet-gitlab#343]
<!--
Thank you for contributing to this project!

- This project has a Contributor Code of Conduct: https://voxpupuli.org/coc/
- Please check that here is no existing issue or PR that addresses your problem.
- Please fill the following form to enable us to help you.
- Our vulnerabilities reporting process is at https://voxpupuli.org/security/

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.14
- Ruby:
- Distribution: 12.10.6
- Module version: 5.0.0
- OS: RHEL 7.6

## What are you seeing

Hiera doesn't seem to parsing correctly and returning in the gitlab.rb as json

Hiera configuration

```
gitlab::gitlab_rails:
  ldap_enabled: true
gitlab::gitlab_rails:
  ldap_servers:
    main:
      label: 'LDAP'
      host: 'adserver-01'
      port: 389
      uid: 'gitlabuser'
      method: 'plain' # "tls" or "ssl" or "plain"
      bind_dn: 'DC=uk'
      password: '$password'
      active_directory: true
      allow_username_or_email_login: true
      block_auto_created_users: false
      base: 'DC=uk'

```
Getting returned in my /etc/gitlab/gitlab.rb

`############################
# gitlab.yml configuration #
############################

gitlab_rails['ldap_servers'] = {"main"=>{"active_directory"=>true, "allow_username_or_email_login"=>true, "base"=>"DC=uk", "bind_dn"=>"DC=uk", "block_auto_created_users"=>false, "host"=>"adserver-01", "label"=>"LDAP", "method"=>"plain", "password"=>"$password", "port"=>389, "uid"=>"gitlabuser"}}
`
