### ISSUE TITLE
Hiera not parsing gitlab.rb and ::gitlab_rails:

### ISSUE THREAD

**Issue by hktyper** [voxpupuli/puppet-gitlab#344]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.14
- Ruby:
- Gitlab: 12.10.6 CE
- Module version: 5.0.0
- OS: RHEL 7.6

## How to reproduce (e.g Puppet code you use)

Hiera

```
gitlab::gitlab_rails:
  ldap_servers:
    main:
      label: 'LDAP'
      host: 'adserver-01'
      port: 389
      uid: 'gitlabuser'
      method: 'plain' # "tls" or "ssl" or "plain"
      bind_dn: 'DC=uk'
      password: '$password'
      active_directory: true
      allow_username_or_email_login: true
      block_auto_created_users: false
      base: 'DC=uk'
```
## What are you seeing

Hiera isn't parsing correctly and returning as a json block instead

```
############################
# gitlab.yml configuration #
############################

gitlab_rails['ldap_servers'] = {"main"=>{"active_directory"=>true, "allow_username_or_email_login"=>true, "base"=>"DC=uk", "bind_dn"=>"DC=uk", "block_auto_created_users"=>false, "host"=>"adserver-01", "label"=>"LDAP", "method"=>"plain", "password"=>"$password", "port"=>389, "uid"=>"gitlabuser"}}
```

## What behaviour did you expect instead

```
############################
# gitlab.yml configuration #
############################

gitlab_rails['ldap_enabled'] = true

gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
  main:
    active_directory: true
    allow_username_or_email_login: true
    base: "DC=uk"
    bind_dn: "DC=uk"
    block_auto_created_users: false
    host: "adserver-01"
    label: "LDAP"
    method: "plain"
    password: "$password"
    port: 389
    uid: "gitlabuser"
EOS
```
