### ISSUE TITLE
repo_gpgcheck fails

### ISSUE THREAD

**Issue by silug** [voxpupuli/puppet-gitlab#401]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.16.0
- Ruby: 2.7.6p219
- Distribution: CentOS Stream 8
- Module version: 4.3.0

## How to reproduce (e.g Puppet code you use)

```puppet
include gitlab
```

## What are you seeing

Package operations in Puppet fail with
```
Error: Failed to download metadata for repo 'gitlab_official_ce': repomd.xml GPG signature verification error: Bad GPG signature
```

## What behaviour did you expect instead

No such errors.

## Any additional information you'd like to impart

This appears to be an upstream repo issue and may not be appropriate to "fix" in this module.

Workaround in hiera:
```yaml
---
lookup_options:
  gitlab::repository_configuration:
    merge:
      strategy: deep

gitlab::repository_configuration:
  yumrepo:
    "gitlab_official_ce":
      repo_gpgcheck: 0
    "gitlab_official_ee":
      repo_gpgcheck: 0
```
